/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PassesRouteImport } from './routes/passes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAttendeesRouteImport } from './routes/admin.attendees'
import { Route as AdminChatRouteImport } from './routes/admin.chat'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminEmailTemplatesRouteImport } from './routes/admin.email-templates'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminInvitationsRouteImport } from './routes/admin.invitations'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminRegistrationsRouteImport } from './routes/admin.registrations'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminScannerRouteImport } from './routes/admin.scanner'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSlidersRouteImport } from './routes/admin.sliders'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as EventEventIdRouteImport } from './routes/event.$eventId'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PassesRoute = PassesRouteImport.update({
  id: '/passes',
  path: '/passes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendeesRoute = AdminAttendeesRouteImport.update({
  id: '/attendees',
  path: '/attendees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailTemplatesRoute = AdminEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvitationsRoute = AdminInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScannerRoute = AdminScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSlidersRoute = AdminSlidersRouteImport.update({
  id: '/sliders',
  path: '/sliders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const EventEventIdRoute = EventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/notifications': typeof NotificationsRoute
  '/passes': typeof PassesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/attendees': typeof AdminAttendeesRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sliders': typeof AdminSlidersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/notifications': typeof NotificationsRoute
  '/passes': typeof PassesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/attendees': typeof AdminAttendeesRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sliders': typeof AdminSlidersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/notifications': typeof NotificationsRoute
  '/passes': typeof PassesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/attendees': typeof AdminAttendeesRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sliders': typeof AdminSlidersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/my-events'
    | '/notifications'
    | '/passes'
    | '/profile'
    | '/register'
    | '/admin/accounts'
    | '/admin/attendance'
    | '/admin/attendees'
    | '/admin/chat'
    | '/admin/clients'
    | '/admin/email-templates'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/invitations'
    | '/admin/notifications'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/scanner'
    | '/admin/settings'
    | '/admin/sliders'
    | '/admin/vendors'
    | '/event/$eventId'
    | '/events/$eventId'
    | '/admin/'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/my-events'
    | '/notifications'
    | '/passes'
    | '/profile'
    | '/register'
    | '/admin/accounts'
    | '/admin/attendance'
    | '/admin/attendees'
    | '/admin/chat'
    | '/admin/clients'
    | '/admin/email-templates'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/invitations'
    | '/admin/notifications'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/scanner'
    | '/admin/settings'
    | '/admin/sliders'
    | '/admin/vendors'
    | '/event/$eventId'
    | '/events/$eventId'
    | '/admin'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/my-events'
    | '/notifications'
    | '/passes'
    | '/profile'
    | '/register'
    | '/admin/accounts'
    | '/admin/attendance'
    | '/admin/attendees'
    | '/admin/chat'
    | '/admin/clients'
    | '/admin/email-templates'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/invitations'
    | '/admin/notifications'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/scanner'
    | '/admin/settings'
    | '/admin/sliders'
    | '/admin/vendors'
    | '/event/$eventId'
    | '/events/$eventId'
    | '/admin/'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MyEventsRoute: typeof MyEventsRoute
  NotificationsRoute: typeof NotificationsRoute
  PassesRoute: typeof PassesRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  EventEventIdRoute: typeof EventEventIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passes': {
      id: '/passes'
      path: '/passes'
      fullPath: '/passes'
      preLoaderRoute: typeof PassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendees': {
      id: '/admin/attendees'
      path: '/attendees'
      fullPath: '/admin/attendees'
      preLoaderRoute: typeof AdminAttendeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-templates': {
      id: '/admin/email-templates'
      path: '/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AdminEmailTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invitations': {
      id: '/admin/invitations'
      path: '/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof AdminInvitationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scanner': {
      id: '/admin/scanner'
      path: '/scanner'
      fullPath: '/admin/scanner'
      preLoaderRoute: typeof AdminScannerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sliders': {
      id: '/admin/sliders'
      path: '/sliders'
      fullPath: '/admin/sliders'
      preLoaderRoute: typeof AdminSlidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/event/$eventId': {
      id: '/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminAttendeesRoute: typeof AdminAttendeesRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminEmailTemplatesRoute: typeof AdminEmailTemplatesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminInvitationsRoute: typeof AdminInvitationsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminScannerRoute: typeof AdminScannerRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSlidersRoute: typeof AdminSlidersRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminAttendeesRoute: AdminAttendeesRoute,
  AdminChatRoute: AdminChatRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminEmailTemplatesRoute: AdminEmailTemplatesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminInvitationsRoute: AdminInvitationsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminScannerRoute: AdminScannerRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSlidersRoute: AdminSlidersRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MyEventsRoute: MyEventsRoute,
  NotificationsRoute: NotificationsRoute,
  PassesRoute: PassesRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  EventEventIdRoute: EventEventIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
